package com.oreon.cerebrum.drugs;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.validator.constraints.Length;
import org.witchcraft.base.entity.BaseEntity;

//Impl 

/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

/**
 * 
 *
 */

@MappedSuperclass
public class AtcDrugBase extends BaseEntity {
	private static final long serialVersionUID = -1623432457L;

	@Column(unique = false)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String code

	;

	@NotNull
	@Length(min = 1, max = 250)
	@Column(unique = false)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String name

	;

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "parent_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<AtcDrug> subcategories = new HashSet<AtcDrug>();

	public void addSubcategorie(AtcDrug subcategorie) {

		subcategorie.setParent((AtcDrug) this);

		this.subcategories.add(subcategorie);
	}

	@Transient
	public List<com.oreon.cerebrum.drugs.AtcDrug> getListSubcategories() {
		return new ArrayList<com.oreon.cerebrum.drugs.AtcDrug>(subcategories);
	}

	//JSF Friendly function to get count of collections
	public int getSubcategoriesCount() {
		return subcategories.size();
	}

	@ManyToOne(optional = true, fetch = FetchType.LAZY)
	@JoinColumn(name = "drug_id", nullable = true, updatable = true)
	protected Drug drug

	;

	@ManyToOne(optional = true, fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", nullable = true, updatable = true)
	protected AtcDrug parent

	;

	public void setCode(String code) {
		this.code = code;
	}

	public String getCode() {

		return code;

	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {

		return name;

	}

	public void setSubcategories(Set<AtcDrug> subcategories) {
		this.subcategories = subcategories;
	}

	public Set<AtcDrug> getSubcategories() {
		return subcategories;
	}

	public void setDrug(Drug drug) {
		this.drug = drug;
	}

	public Drug getDrug() {

		return drug;

	}

	public void setParent(AtcDrug parent) {
		this.parent = parent;
	}

	public AtcDrug getParent() {

		return parent;

	}

	@Transient
	public String getDisplayName() {
		try {
			return name;
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

	//Empty setter , needed for richfaces autocomplete to work 
	public void setDisplayName(String name) {
	}

	/** This method is used by hibernate full text search - override to add additional fields
	 * @see org.witchcraft.model.support.BaseEntity#retrieveSearchableFieldsArray()
	 */
	@Override
	public List<String> listSearchableFields() {
		List<String> listSearchableFields = new ArrayList<String>();
		listSearchableFields.addAll(super.listSearchableFields());

		listSearchableFields.add("code");

		listSearchableFields.add("name");

		listSearchableFields.add("subcategories.code");

		listSearchableFields.add("subcategories.name");

		return listSearchableFields;
	}

	@Field(index = Index.YES, name = "searchData")
	@Analyzer(definition = "entityAnalyzer")
	public String getSearchData() {
		StringBuilder builder = new StringBuilder();

		builder.append(getCode() + " ");

		builder.append(getName() + " ");

		if (getDrug() != null)
			builder.append("drug:" + getDrug().getDisplayName() + " ");

		if (getParent() != null)
			builder.append("parent:" + getParent().getDisplayName() + " ");

		for (BaseEntity e : subcategories) {
			builder.append(e.getDisplayName() + " ");
		}

		return builder.toString();
	}

	/*
	<param name="drugId" value="#{drugId}" />
	<param name="parentId" value="#{parentId}" />
	
	 */

}
