
/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

package com.oreon.cerebrum.employee;

import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.Filters;

@Entity
@Table(name = "employee")
@Filters({@Filter(name = "archiveFilterDef"), @Filter(name = "tenantFilterDef")})
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@XmlRootElement
public class Employee extends EmployeeBase implements java.io.Serializable {
	private static final long serialVersionUID = -426154292L; 
	
	@Transient
	public String getName(){
		return firstName + " " +  lastName;
	}
}
