package com.oreon.cerebrum.employee;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.Transient;

import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;

//Impl 

/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

/**
 * 
 *
 */

@MappedSuperclass
public class NurseBase extends com.oreon.cerebrum.employee.Employee {
	private static final long serialVersionUID = -613325953L;

	@ManyToOne(optional = true, fetch = FetchType.LAZY)
	@JoinColumn(name = "nurseSpecialty_id", nullable = true, updatable = true)
	protected NurseSpecialty nurseSpecialty

	;

	public void setNurseSpecialty(NurseSpecialty nurseSpecialty) {
		this.nurseSpecialty = nurseSpecialty;
	}

	public NurseSpecialty getNurseSpecialty() {

		return nurseSpecialty;

	}

	@Transient
	public String getDisplayName() {
		try {
			return super.getDisplayName();
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

	//Empty setter , needed for richfaces autocomplete to work 
	public void setDisplayName(String name) {
	}

	/** This method is used by hibernate full text search - override to add additional fields
	 * @see org.witchcraft.model.support.BaseEntity#retrieveSearchableFieldsArray()
	 */
	@Override
	public List<String> listSearchableFields() {
		List<String> listSearchableFields = new ArrayList<String>();
		listSearchableFields.addAll(super.listSearchableFields());

		return listSearchableFields;
	}

	@Field(index = Index.YES, name = "searchData")
	@Analyzer(definition = "entityAnalyzer")
	public String getSearchData() {
		StringBuilder builder = new StringBuilder();

		if (getNurseSpecialty() != null)
			builder.append("nurseSpecialty:"
					+ getNurseSpecialty().getDisplayName() + " ");

		return builder.toString();
	}

	/*
	<param name="nurseSpecialtyId" value="#{nurseSpecialtyId}" />
	
	 */

}
