package com.oreon.cerebrum.admission;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Date;

import com.google.common.base.Objects;

import javax.persistence.*;
import org.hibernate.validator.*;

import com.google.common.base.Objects;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import org.apache.solr.analysis.LowerCaseFilterFactory;
import org.apache.solr.analysis.SnowballPorterFilterFactory;
import org.apache.solr.analysis.StandardTokenizerFactory;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.Formula;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.Cascade;

import org.hibernate.search.annotations.AnalyzerDef;
import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Boost;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Parameter;
import org.hibernate.search.annotations.TokenFilterDef;
import org.hibernate.search.annotations.TokenizerDef;
import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.IndexedEmbedded;

import org.hibernate.annotations.Filter;

import org.hibernate.validator.constraints.*;
import javax.validation.constraints.*;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.jboss.seam.annotations.Name;

import org.witchcraft.model.support.audit.Auditable;

import org.witchcraft.utils.*;

import org.witchcraft.base.entity.FileAttachment;
import org.witchcraft.base.entity.BaseEntity;

import com.oreon.cerebrum.ProjectUtils;

//Impl 

/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

/**
 * 
 *
 */

@MappedSuperclass
public class AdmissionBase extends BaseEntity {
	private static final long serialVersionUID = -919788764L;

	@ManyToOne(optional = false, fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false, updatable = true)
	protected com.oreon.cerebrum.patient.Patient patient = new com.oreon.cerebrum.patient.Patient();

	@Lob
	@Column(unique = false)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String admissionNote

	;

	@Column(name = "dischargeDate", unique = false)
	protected Date dischargeDate

	;

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "admission_ID", nullable = false)
	@OrderBy("id DESC")
	private Set<BedStay> bedStays = new HashSet<BedStay>();

	public void addBedStay(BedStay bedStay) {

		bedStay.setAdmission((Admission) this);

		this.bedStays.add(bedStay);
	}

	@Transient
	public List<com.oreon.cerebrum.admission.BedStay> getListBedStays() {
		return new ArrayList<com.oreon.cerebrum.admission.BedStay>(bedStays);
	}

	@Transient
	public String getListBedStaysAsString() {
		StringBuilder result = new StringBuilder();

		List<com.oreon.cerebrum.admission.BedStay> tempList = getListBedStays();
		int count = 0;
		for (com.oreon.cerebrum.admission.BedStay bedStay : tempList) {
			++count;
			result.append(bedStay.getDisplayName());
			if (count < tempList.size())
				result.append(", ");
		}

		return result.toString();
	}

	//JSF Friendly function to get count of collections
	public int getBedStaysCount() {
		return bedStays.size();
	}

	@Lob
	@Column(unique = false)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String dischargeNote

	;

	@Column(unique = false)
	protected com.oreon.cerebrum.patient.DischargeCode dischargeCode

	;

	@Transient
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String currentBed

	;

	@Column(unique = false)
	protected Boolean isCurrent

	;

	@ManyToOne(optional = true, fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice_id", nullable = true, updatable = true)
	protected com.oreon.cerebrum.billing.Invoice invoice

	;

	public void setPatient(com.oreon.cerebrum.patient.Patient patient) {
		this.patient = patient;
	}

	public com.oreon.cerebrum.patient.Patient getPatient() {

		return patient;

	}

	public void setAdmissionNote(String admissionNote) {
		this.admissionNote = admissionNote;
	}

	public String getAdmissionNote() {

		return admissionNote;

	}

	public void setDischargeDate(Date dischargeDate) {
		this.dischargeDate = dischargeDate;
	}

	public Date getDischargeDate() {

		return dischargeDate;

	}

	public void setBedStays(Set<BedStay> bedStays) {
		this.bedStays = bedStays;
	}

	public Set<BedStay> getBedStays() {
		return bedStays;
	}

	public void setDischargeNote(String dischargeNote) {
		this.dischargeNote = dischargeNote;
	}

	public String getDischargeNote() {

		return dischargeNote;

	}

	public void setDischargeCode(
			com.oreon.cerebrum.patient.DischargeCode dischargeCode) {
		this.dischargeCode = dischargeCode;
	}

	public com.oreon.cerebrum.patient.DischargeCode getDischargeCode() {

		return dischargeCode;

	}

	public void setCurrentBed(String currentBed) {
		this.currentBed = currentBed;
	}

	public String getCurrentBed() {

		try {
			return patient.getBed().getDisplayName();
		} catch (Exception e) {

			return "";

		}

	}

	public void setIsCurrent(Boolean isCurrent) {
		this.isCurrent = isCurrent;
	}

	public Boolean getIsCurrent() {

		return isCurrent;

	}

	public void setInvoice(com.oreon.cerebrum.billing.Invoice invoice) {
		this.invoice = invoice;
	}

	public com.oreon.cerebrum.billing.Invoice getInvoice() {

		return invoice;

	}

	@Transient
	public String getDisplayName() {
		try {
			return currentBed;
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

	@Transient
	public String getAdmissionNoteAbbreviated() {
		try {
			return org.apache.commons.lang.WordUtils.abbreviate(admissionNote
					.trim(), 100, 200, "...");
		} catch (Exception e) {
			return admissionNote != null ? admissionNote : "";
		}
	}

	@Transient
	public String getDischargeNoteAbbreviated() {
		try {
			return org.apache.commons.lang.WordUtils.abbreviate(dischargeNote
					.trim(), 100, 200, "...");
		} catch (Exception e) {
			return dischargeNote != null ? dischargeNote : "";
		}
	}

	//Empty setter , needed for richfaces autocomplete to work 
	public void setDisplayName(String name) {
	}

	/** This method is used by hibernate full text search - override to add additional fields
	 * @see org.witchcraft.model.support.BaseEntity#retrieveSearchableFieldsArray()
	 */
	@Override
	public List<String> listSearchableFields() {
		List<String> listSearchableFields = new ArrayList<String>();
		listSearchableFields.addAll(super.listSearchableFields());

		listSearchableFields.add("admissionNote");

		listSearchableFields.add("dischargeNote");

		listSearchableFields.add("currentBed");

		return listSearchableFields;
	}

	@Field(index = Index.YES, name = "searchData")
	@Analyzer(definition = "entityAnalyzer")
	public String getSearchData() {
		StringBuilder builder = new StringBuilder();

		builder.append(getAdmissionNote() + " ");

		builder.append(getDischargeNote() + " ");

		builder.append(getCurrentBed() + " ");

		if (getPatient() != null)
			builder.append("patient:" + getPatient().getDisplayName() + " ");

		if (getInvoice() != null)
			builder.append("invoice:" + getInvoice().getDisplayName() + " ");

		for (BaseEntity e : bedStays) {
			builder.append(e.getDisplayName() + " ");
		}

		return builder.toString();
	}

	/*
	<param name="patientId" value="#{patientId}" />
	<param name="invoiceId" value="#{invoiceId}" />
	
	 */

}
