
/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

package com.oreon.cerebrum.encounter;

import javax.persistence.Embeddable;

@Embeddable
public class TestResults extends TestResultsBase
		implements
			java.io.Serializable {
	private static final long serialVersionUID = -1311421045L;
}
