
/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

package com.oreon.cerebrum.encounter;

import javax.persistence.Embeddable;

@Embeddable
public class Vitals extends VitalsBase implements java.io.Serializable {
	private static final long serialVersionUID = -946647828L;
}
