package com.oreon.cerebrum.encounter;

import javax.persistence.Column;
import javax.persistence.MappedSuperclass;
import javax.persistence.Transient;

//Impl 

/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

/**
 * 
 *
 */

@MappedSuperclass
public class VitalsBase {

	@Column(unique = false)
	protected Integer SysBP

	;

	@Column(unique = false)
	protected Integer DiasBP

	;

	@Column(unique = false)
	protected Double Temperature

	;

	@Column(unique = false)
	protected Integer Pulse

	;

	@Column(unique = false)
	protected Integer RespirationRate

	;

	public void setSysBP(Integer SysBP) {
		this.SysBP = SysBP;
	}

	public Integer getSysBP() {

		return SysBP;

	}

	public void setDiasBP(Integer DiasBP) {
		this.DiasBP = DiasBP;
	}

	public Integer getDiasBP() {

		return DiasBP;

	}

	public void setTemperature(Double Temperature) {
		this.Temperature = Temperature;
	}

	public Double getTemperature() {

		return Temperature;

	}

	public void setPulse(Integer Pulse) {
		this.Pulse = Pulse;
	}

	public Integer getPulse() {

		return Pulse;

	}

	public void setRespirationRate(Integer RespirationRate) {
		this.RespirationRate = RespirationRate;
	}

	public Integer getRespirationRate() {

		return RespirationRate;

	}

	@Transient
	public String getDisplayName() {
		try {
			return SysBP + "";
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

}
