package com.oreon.cerebrum.prescription;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.Lob;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.validator.constraints.Length;
import org.witchcraft.base.entity.BaseEntity;

//Impl 

/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

/**
 * 
 *
 */

@MappedSuperclass
public class PrescriptionTemplateBase extends BaseEntity {
	private static final long serialVersionUID = -1126681998L;

	@NotNull
	@Length(min = 1, max = 250)
	@Column(unique = true)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String name

	;

	@Lob
	@Column(unique = false)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String directivesForPatient

	;

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "prescriptionTemplate_ID", nullable = false)
	@OrderBy("id DESC")
	private Set<PrescriptionItemTemplate> prescriptionItemTemplates = new HashSet<PrescriptionItemTemplate>();

	public void addPrescriptionItemTemplate(
			PrescriptionItemTemplate prescriptionItemTemplate) {

		prescriptionItemTemplate
				.setPrescriptionTemplate((PrescriptionTemplate) this);

		this.prescriptionItemTemplates.add(prescriptionItemTemplate);
	}

	@Transient
	public List<com.oreon.cerebrum.prescription.PrescriptionItemTemplate> getListPrescriptionItemTemplates() {
		return new ArrayList<com.oreon.cerebrum.prescription.PrescriptionItemTemplate>(
				prescriptionItemTemplates);
	}

	//JSF Friendly function to get count of collections
	public int getPrescriptionItemTemplatesCount() {
		return prescriptionItemTemplates.size();
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {

		return name;

	}

	public void setDirectivesForPatient(String directivesForPatient) {
		this.directivesForPatient = directivesForPatient;
	}

	public String getDirectivesForPatient() {

		return directivesForPatient;

	}

	public void setPrescriptionItemTemplates(
			Set<PrescriptionItemTemplate> prescriptionItemTemplates) {
		this.prescriptionItemTemplates = prescriptionItemTemplates;
	}

	public Set<PrescriptionItemTemplate> getPrescriptionItemTemplates() {
		return prescriptionItemTemplates;
	}

	@Transient
	public String getDisplayName() {
		try {
			return name;
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

	@Transient
	public String getDirectivesForPatientAbbreviated() {
		try {
			return org.apache.commons.lang.WordUtils.abbreviate(
					directivesForPatient.trim(), 100, 200, "...");
		} catch (Exception e) {
			return directivesForPatient != null ? directivesForPatient : "";
		}
	}

	//Empty setter , needed for richfaces autocomplete to work 
	public void setDisplayName(String name) {
	}

	/** This method is used by hibernate full text search - override to add additional fields
	 * @see org.witchcraft.model.support.BaseEntity#retrieveSearchableFieldsArray()
	 */
	@Override
	public List<String> listSearchableFields() {
		List<String> listSearchableFields = new ArrayList<String>();
		listSearchableFields.addAll(super.listSearchableFields());

		listSearchableFields.add("name");

		listSearchableFields.add("directivesForPatient");

		listSearchableFields.add("prescriptionItemTemplates.strength");

		listSearchableFields.add("prescriptionItemTemplates.remarks");

		listSearchableFields.add("prescriptionItemTemplates.brandName");

		return listSearchableFields;
	}

	@Field(index = Index.YES, name = "searchData")
	@Analyzer(definition = "entityAnalyzer")
	public String getSearchData() {
		StringBuilder builder = new StringBuilder();

		builder.append(getName() + " ");

		builder.append(getDirectivesForPatient() + " ");

		for (BaseEntity e : prescriptionItemTemplates) {
			builder.append(e.getDisplayName() + " ");
		}

		return builder.toString();
	}

	/*
	
	 */

}
