
/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

package com.oreon.cerebrum.codes;

import javax.persistence.MappedSuperclass;

@MappedSuperclass
public class AbstractCode extends AbstractCodeBase
		implements
			java.io.Serializable {
	private static final long serialVersionUID = 971125289L;
}
