package com.oreon.cerebrum.codes;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Transient;

import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.witchcraft.base.entity.BaseEntity;

//Impl 

/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

/**
 * 
 *
 */

@MappedSuperclass
public class SectionBase extends com.oreon.cerebrum.codes.AbstractCode {
	private static final long serialVersionUID = -1956883681L;

	@ManyToOne(optional = false, fetch = FetchType.LAZY)
	@JoinColumn(name = "chapter_id", nullable = false, updatable = true)
	protected Chapter chapter

	;

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "section_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<Code> codes = new HashSet<Code>();

	public void addCode(Code code) {

		code.setSection((Section) this);

		this.codes.add(code);
	}

	@Transient
	public List<com.oreon.cerebrum.codes.Code> getListCodes() {
		return new ArrayList<com.oreon.cerebrum.codes.Code>(codes);
	}

	//JSF Friendly function to get count of collections
	public int getCodesCount() {
		return codes.size();
	}

	public void setChapter(Chapter chapter) {
		this.chapter = chapter;
	}

	public Chapter getChapter() {

		return chapter;

	}

	public void setCodes(Set<Code> codes) {
		this.codes = codes;
	}

	public Set<Code> getCodes() {
		return codes;
	}

	@Transient
	public String getDisplayName() {
		try {
			return super.getDisplayName();
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

	//Empty setter , needed for richfaces autocomplete to work 
	public void setDisplayName(String name) {
	}

	/** This method is used by hibernate full text search - override to add additional fields
	 * @see org.witchcraft.model.support.BaseEntity#retrieveSearchableFieldsArray()
	 */
	@Override
	public List<String> listSearchableFields() {
		List<String> listSearchableFields = new ArrayList<String>();
		listSearchableFields.addAll(super.listSearchableFields());

		listSearchableFields.add("codes.includes");

		listSearchableFields.add("codes.notIncludedHere");

		listSearchableFields.add("codes.codeFirst");

		listSearchableFields.add("codes.notCodedHere");

		listSearchableFields.add("codes.codeAlso");

		return listSearchableFields;
	}

	@Field(index = Index.YES, name = "searchData")
	@Analyzer(definition = "entityAnalyzer")
	public String getSearchData() {
		StringBuilder builder = new StringBuilder();

		if (getChapter() != null)
			builder.append("chapter:" + getChapter().getDisplayName() + " ");

		for (BaseEntity e : codes) {
			builder.append(e.getDisplayName() + " ");
		}

		return builder.toString();
	}

	/*
	<param name="chapterId" value="#{chapterId}" />
	
	 */

}
