
/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

package com.oreon.cerebrum.patient;

import javax.persistence.Embeddable;

import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Fields;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;

@Embeddable
@Indexed
public class ContactDetails extends ContactDetailsBase
		implements
			java.io.Serializable {
	private static final long serialVersionUID = 243784283L;
	
	
	
	@Override
	@Fields( {
			@Field(index = Index.YES),
			@Field(index = Index.YES, name = "phone:ngrams", analyzer = @Analyzer(definition = "ngrams")) })
	public String getPrimaryPhone() {
		
		return super.getPrimaryPhone();
	}
}
