package com.oreon.cerebrum.patient;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Date;

import com.google.common.base.Objects;

import javax.persistence.*;
import org.hibernate.validator.*;

import com.google.common.base.Objects;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import org.apache.solr.analysis.LowerCaseFilterFactory;
import org.apache.solr.analysis.SnowballPorterFilterFactory;
import org.apache.solr.analysis.StandardTokenizerFactory;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.Formula;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.Cascade;

import org.hibernate.search.annotations.AnalyzerDef;
import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Boost;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Parameter;
import org.hibernate.search.annotations.TokenFilterDef;
import org.hibernate.search.annotations.TokenizerDef;
import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.IndexedEmbedded;

import org.hibernate.annotations.Filter;

import org.hibernate.validator.constraints.*;
import javax.validation.constraints.*;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.jboss.seam.annotations.Name;

import org.witchcraft.model.support.audit.Auditable;

import org.witchcraft.utils.*;

import org.witchcraft.base.entity.FileAttachment;
import org.witchcraft.base.entity.BaseEntity;

import com.oreon.cerebrum.ProjectUtils;

//Impl 

/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

/**
 * 
 *
 */

@MappedSuperclass
public class HistoryBase {

	@Lob
	@Column(unique = false)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String medicalHistory

	;

	@Lob
	@Column(unique = false)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String socialHistory

	;

	@Lob
	@Column(unique = false)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String familyHistory

	;

	@Lob
	@Column(unique = false)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String medications

	;

	@Lob
	@Column(unique = false)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String allergies

	;

	public void setMedicalHistory(String medicalHistory) {
		this.medicalHistory = medicalHistory;
	}

	public String getMedicalHistory() {

		return medicalHistory;

	}

	public void setSocialHistory(String socialHistory) {
		this.socialHistory = socialHistory;
	}

	public String getSocialHistory() {

		return socialHistory;

	}

	public void setFamilyHistory(String familyHistory) {
		this.familyHistory = familyHistory;
	}

	public String getFamilyHistory() {

		return familyHistory;

	}

	public void setMedications(String medications) {
		this.medications = medications;
	}

	public String getMedications() {

		return medications;

	}

	public void setAllergies(String allergies) {
		this.allergies = allergies;
	}

	public String getAllergies() {

		return allergies;

	}

	@Transient
	public String getDisplayName() {
		try {
			return medicalHistory + "";
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

	@Transient
	public String getMedicalHistoryAbbreviated() {
		try {
			return org.apache.commons.lang.WordUtils.abbreviate(medicalHistory
					.trim(), 100, 200, "...");
		} catch (Exception e) {
			return medicalHistory != null ? medicalHistory : "";
		}
	}

	@Transient
	public String getSocialHistoryAbbreviated() {
		try {
			return org.apache.commons.lang.WordUtils.abbreviate(socialHistory
					.trim(), 100, 200, "...");
		} catch (Exception e) {
			return socialHistory != null ? socialHistory : "";
		}
	}

	@Transient
	public String getFamilyHistoryAbbreviated() {
		try {
			return org.apache.commons.lang.WordUtils.abbreviate(familyHistory
					.trim(), 100, 200, "...");
		} catch (Exception e) {
			return familyHistory != null ? familyHistory : "";
		}
	}

	@Transient
	public String getMedicationsAbbreviated() {
		try {
			return org.apache.commons.lang.WordUtils.abbreviate(medications
					.trim(), 100, 200, "...");
		} catch (Exception e) {
			return medications != null ? medications : "";
		}
	}

	@Transient
	public String getAllergiesAbbreviated() {
		try {
			return org.apache.commons.lang.WordUtils.abbreviate(allergies
					.trim(), 100, 200, "...");
		} catch (Exception e) {
			return allergies != null ? allergies : "";
		}
	}

}
