package com.oreon.cerebrum.patient;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Date;

import com.google.common.base.Objects;

import javax.persistence.*;
import org.hibernate.validator.*;

import com.google.common.base.Objects;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import org.apache.solr.analysis.LowerCaseFilterFactory;
import org.apache.solr.analysis.SnowballPorterFilterFactory;
import org.apache.solr.analysis.StandardTokenizerFactory;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.Formula;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.Cascade;

import org.hibernate.search.annotations.AnalyzerDef;
import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Boost;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Parameter;
import org.hibernate.search.annotations.TokenFilterDef;
import org.hibernate.search.annotations.TokenizerDef;
import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.IndexedEmbedded;

import org.hibernate.annotations.Filter;

import org.hibernate.validator.constraints.*;
import javax.validation.constraints.*;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.jboss.seam.annotations.Name;

import org.witchcraft.model.support.audit.Auditable;

import org.witchcraft.utils.*;

import org.witchcraft.base.entity.FileAttachment;
import org.witchcraft.base.entity.BaseEntity;

import com.oreon.cerebrum.ProjectUtils;

//Impl 

/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

/**
 * 
 *
 */

@MappedSuperclass
public class PatientBase extends com.oreon.cerebrum.patient.Person {
	private static final long serialVersionUID = -586507236L;

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "patient_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<com.oreon.cerebrum.admission.Admission> admissions = new HashSet<com.oreon.cerebrum.admission.Admission>();

	public void addAdmission(com.oreon.cerebrum.admission.Admission admission) {

		admission.setPatient((Patient) this);

		this.admissions.add(admission);
	}

	@Transient
	public List<com.oreon.cerebrum.admission.Admission> getListAdmissions() {
		return new ArrayList<com.oreon.cerebrum.admission.Admission>(admissions);
	}

	@Transient
	public String getListAdmissionsAsString() {
		StringBuilder result = new StringBuilder();

		List<com.oreon.cerebrum.admission.Admission> tempList = getListAdmissions();
		int count = 0;
		for (com.oreon.cerebrum.admission.Admission admission : tempList) {
			++count;
			result.append(admission.getDisplayName());
			if (count < tempList.size())
				result.append(", ");
		}

		return result.toString();
	}

	//JSF Friendly function to get count of collections
	public int getAdmissionsCount() {
		return admissions.size();
	}

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "patient_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<com.oreon.cerebrum.prescription.Prescription> prescriptions = new HashSet<com.oreon.cerebrum.prescription.Prescription>();

	public void addPrescription(
			com.oreon.cerebrum.prescription.Prescription prescription) {

		prescription.setPatient((Patient) this);

		this.prescriptions.add(prescription);
	}

	@Transient
	public List<com.oreon.cerebrum.prescription.Prescription> getListPrescriptions() {
		return new ArrayList<com.oreon.cerebrum.prescription.Prescription>(
				prescriptions);
	}

	@Transient
	public String getListPrescriptionsAsString() {
		StringBuilder result = new StringBuilder();

		List<com.oreon.cerebrum.prescription.Prescription> tempList = getListPrescriptions();
		int count = 0;
		for (com.oreon.cerebrum.prescription.Prescription prescription : tempList) {
			++count;
			result.append(prescription.getDisplayName());
			if (count < tempList.size())
				result.append(", ");
		}

		return result.toString();
	}

	//JSF Friendly function to get count of collections
	public int getPrescriptionsCount() {
		return prescriptions.size();
	}

	@IndexedEmbedded
	@AttributeOverrides({

			@AttributeOverride(name = "streetAddress", column = @Column(name = "address_streetAddress")),

			@AttributeOverride(name = "city", column = @Column(name = "address_city")),

			@AttributeOverride(name = "State", column = @Column(name = "address_State")),

			@AttributeOverride(name = "phone", column = @Column(name = "address_phone"))

	})
	protected Address address = new Address();

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "patient_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<com.oreon.cerebrum.unusualoccurences.UnusualOccurence> unusualOccurences = new HashSet<com.oreon.cerebrum.unusualoccurences.UnusualOccurence>();

	public void addUnusualOccurence(
			com.oreon.cerebrum.unusualoccurences.UnusualOccurence unusualOccurence) {

		unusualOccurence.setPatient((Patient) this);

		this.unusualOccurences.add(unusualOccurence);
	}

	@Transient
	public List<com.oreon.cerebrum.unusualoccurences.UnusualOccurence> getListUnusualOccurences() {
		return new ArrayList<com.oreon.cerebrum.unusualoccurences.UnusualOccurence>(
				unusualOccurences);
	}

	@Transient
	public String getListUnusualOccurencesAsString() {
		StringBuilder result = new StringBuilder();

		List<com.oreon.cerebrum.unusualoccurences.UnusualOccurence> tempList = getListUnusualOccurences();
		int count = 0;
		for (com.oreon.cerebrum.unusualoccurences.UnusualOccurence unusualOccurence : tempList) {
			++count;
			result.append(unusualOccurence.getDisplayName());
			if (count < tempList.size())
				result.append(", ");
		}

		return result.toString();
	}

	//JSF Friendly function to get count of collections
	public int getUnusualOccurencesCount() {
		return unusualOccurences.size();
	}

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "patient_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<PatientDocument> patientDocuments = new HashSet<PatientDocument>();

	public void addPatientDocument(PatientDocument patientDocument) {

		patientDocument.setPatient((Patient) this);

		this.patientDocuments.add(patientDocument);
	}

	@Transient
	public List<com.oreon.cerebrum.patient.PatientDocument> getListPatientDocuments() {
		return new ArrayList<com.oreon.cerebrum.patient.PatientDocument>(
				patientDocuments);
	}

	@Transient
	public String getListPatientDocumentsAsString() {
		StringBuilder result = new StringBuilder();

		List<com.oreon.cerebrum.patient.PatientDocument> tempList = getListPatientDocuments();
		int count = 0;
		for (com.oreon.cerebrum.patient.PatientDocument patientDocument : tempList) {
			++count;
			result.append(patientDocument.getDisplayName());
			if (count < tempList.size())
				result.append(", ");
		}

		return result.toString();
	}

	//JSF Friendly function to get count of collections
	public int getPatientDocumentsCount() {
		return patientDocuments.size();
	}

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "patient_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<Allergy> allergys = new HashSet<Allergy>();

	public void addAllergy(Allergy allergy) {

		allergy.setPatient((Patient) this);

		this.allergys.add(allergy);
	}

	@Transient
	public List<com.oreon.cerebrum.patient.Allergy> getListAllergys() {
		return new ArrayList<com.oreon.cerebrum.patient.Allergy>(allergys);
	}

	@Transient
	public String getListAllergysAsString() {
		StringBuilder result = new StringBuilder();

		List<com.oreon.cerebrum.patient.Allergy> tempList = getListAllergys();
		int count = 0;
		for (com.oreon.cerebrum.patient.Allergy allergy : tempList) {
			++count;
			result.append(allergy.getDisplayName());
			if (count < tempList.size())
				result.append(", ");
		}

		return result.toString();
	}

	//JSF Friendly function to get count of collections
	public int getAllergysCount() {
		return allergys.size();
	}

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "patient_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<Immunization> immunizations = new HashSet<Immunization>();

	public void addImmunization(Immunization immunization) {

		immunization.setPatient((Patient) this);

		this.immunizations.add(immunization);
	}

	@Transient
	public List<com.oreon.cerebrum.patient.Immunization> getListImmunizations() {
		return new ArrayList<com.oreon.cerebrum.patient.Immunization>(
				immunizations);
	}

	@Transient
	public String getListImmunizationsAsString() {
		StringBuilder result = new StringBuilder();

		List<com.oreon.cerebrum.patient.Immunization> tempList = getListImmunizations();
		int count = 0;
		for (com.oreon.cerebrum.patient.Immunization immunization : tempList) {
			++count;
			result.append(immunization.getDisplayName());
			if (count < tempList.size())
				result.append(", ");
		}

		return result.toString();
	}

	//JSF Friendly function to get count of collections
	public int getImmunizationsCount() {
		return immunizations.size();
	}

	@Column(unique = false)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String healthNumber

	;

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "patient_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<VitalValue> vitalValues = new HashSet<VitalValue>();

	public void addVitalValue(VitalValue vitalValue) {

		vitalValue.setPatient((Patient) this);

		this.vitalValues.add(vitalValue);
	}

	@Transient
	public List<com.oreon.cerebrum.patient.VitalValue> getListVitalValues() {
		return new ArrayList<com.oreon.cerebrum.patient.VitalValue>(vitalValues);
	}

	@Transient
	public String getListVitalValuesAsString() {
		StringBuilder result = new StringBuilder();

		List<com.oreon.cerebrum.patient.VitalValue> tempList = getListVitalValues();
		int count = 0;
		for (com.oreon.cerebrum.patient.VitalValue vitalValue : tempList) {
			++count;
			result.append(vitalValue.getDisplayName());
			if (count < tempList.size())
				result.append(", ");
		}

		return result.toString();
	}

	//JSF Friendly function to get count of collections
	public int getVitalValuesCount() {
		return vitalValues.size();
	}

	@IndexedEmbedded
	@AttributeOverrides({

			@AttributeOverride(name = "medicalHistory", column = @Column(name = "history_medicalHistory")),

			@AttributeOverride(name = "socialHistory", column = @Column(name = "history_socialHistory")),

			@AttributeOverride(name = "familyHistory", column = @Column(name = "history_familyHistory")),

			@AttributeOverride(name = "medications", column = @Column(name = "history_medications")),

			@AttributeOverride(name = "allergies", column = @Column(name = "history_allergies"))

	})
	protected History history = new History();

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "patient_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<com.oreon.cerebrum.encounter.Encounter> encounters = new HashSet<com.oreon.cerebrum.encounter.Encounter>();

	public void addEncounter(com.oreon.cerebrum.encounter.Encounter encounter) {

		encounter.setPatient((Patient) this);

		this.encounters.add(encounter);
	}

	@Transient
	public List<com.oreon.cerebrum.encounter.Encounter> getListEncounters() {
		return new ArrayList<com.oreon.cerebrum.encounter.Encounter>(encounters);
	}

	@Transient
	public String getListEncountersAsString() {
		StringBuilder result = new StringBuilder();

		List<com.oreon.cerebrum.encounter.Encounter> tempList = getListEncounters();
		int count = 0;
		for (com.oreon.cerebrum.encounter.Encounter encounter : tempList) {
			++count;
			result.append(encounter.getDisplayName());
			if (count < tempList.size())
				result.append(", ");
		}

		return result.toString();
	}

	//JSF Friendly function to get count of collections
	public int getEncountersCount() {
		return encounters.size();
	}

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "patient_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<com.oreon.cerebrum.charts.AppliedChart> appliedCharts = new HashSet<com.oreon.cerebrum.charts.AppliedChart>();

	public void addAppliedChart(
			com.oreon.cerebrum.charts.AppliedChart appliedChart) {

		appliedChart.setPatient((Patient) this);

		this.appliedCharts.add(appliedChart);
	}

	@Transient
	public List<com.oreon.cerebrum.charts.AppliedChart> getListAppliedCharts() {
		return new ArrayList<com.oreon.cerebrum.charts.AppliedChart>(
				appliedCharts);
	}

	@Transient
	public String getListAppliedChartsAsString() {
		StringBuilder result = new StringBuilder();

		List<com.oreon.cerebrum.charts.AppliedChart> tempList = getListAppliedCharts();
		int count = 0;
		for (com.oreon.cerebrum.charts.AppliedChart appliedChart : tempList) {
			++count;
			result.append(appliedChart.getDisplayName());
			if (count < tempList.size())
				result.append(", ");
		}

		return result.toString();
	}

	//JSF Friendly function to get count of collections
	public int getAppliedChartsCount() {
		return appliedCharts.size();
	}

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "patient_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<com.oreon.cerebrum.charts.ChartProcedure> chartProcedures = new HashSet<com.oreon.cerebrum.charts.ChartProcedure>();

	public void addChartProcedure(
			com.oreon.cerebrum.charts.ChartProcedure chartProcedure) {

		chartProcedure.setPatient((Patient) this);

		this.chartProcedures.add(chartProcedure);
	}

	@Transient
	public List<com.oreon.cerebrum.charts.ChartProcedure> getListChartProcedures() {
		return new ArrayList<com.oreon.cerebrum.charts.ChartProcedure>(
				chartProcedures);
	}

	@Transient
	public String getListChartProceduresAsString() {
		StringBuilder result = new StringBuilder();

		List<com.oreon.cerebrum.charts.ChartProcedure> tempList = getListChartProcedures();
		int count = 0;
		for (com.oreon.cerebrum.charts.ChartProcedure chartProcedure : tempList) {
			++count;
			result.append(chartProcedure.getDisplayName());
			if (count < tempList.size())
				result.append(", ");
		}

		return result.toString();
	}

	//JSF Friendly function to get count of collections
	public int getChartProceduresCount() {
		return chartProcedures.size();
	}

	@OneToOne(optional = true, fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "bed_id", nullable = true, updatable = true)
	protected com.oreon.cerebrum.facility.Bed bed

	;

	@ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
	@JoinTable(name = "patients_chronicConditions", joinColumns = @JoinColumn(name = "patients_ID"), inverseJoinColumns = @JoinColumn(name = "chronicConditions_ID"))
	private Set<com.oreon.cerebrum.ddx.ChronicCondition> chronicConditions = new HashSet<com.oreon.cerebrum.ddx.ChronicCondition>();

	public void addChronicCondition(
			com.oreon.cerebrum.ddx.ChronicCondition chronicCondition) {

		this.chronicConditions.add(chronicCondition);
	}

	@Transient
	public List<com.oreon.cerebrum.ddx.ChronicCondition> getListChronicConditions() {
		return new ArrayList<com.oreon.cerebrum.ddx.ChronicCondition>(
				chronicConditions);
	}

	@Transient
	public String getListChronicConditionsAsString() {
		StringBuilder result = new StringBuilder();

		List<com.oreon.cerebrum.ddx.ChronicCondition> tempList = getListChronicConditions();
		int count = 0;
		for (com.oreon.cerebrum.ddx.ChronicCondition chronicCondition : tempList) {
			++count;
			result.append(chronicCondition.getDisplayName());
			if (count < tempList.size())
				result.append(", ");
		}

		return result.toString();
	}

	//JSF Friendly function to get count of collections
	public int getChronicConditionsCount() {
		return chronicConditions.size();
	}

	public void setAdmissions(
			Set<com.oreon.cerebrum.admission.Admission> admissions) {
		this.admissions = admissions;
	}

	public Set<com.oreon.cerebrum.admission.Admission> getAdmissions() {
		return admissions;
	}

	public void setPrescriptions(
			Set<com.oreon.cerebrum.prescription.Prescription> prescriptions) {
		this.prescriptions = prescriptions;
	}

	public Set<com.oreon.cerebrum.prescription.Prescription> getPrescriptions() {
		return prescriptions;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Address getAddress() {

		if (address == null)
			address = new com.oreon.cerebrum.patient.Address();
		return address;

	}

	public void setUnusualOccurences(
			Set<com.oreon.cerebrum.unusualoccurences.UnusualOccurence> unusualOccurences) {
		this.unusualOccurences = unusualOccurences;
	}

	public Set<com.oreon.cerebrum.unusualoccurences.UnusualOccurence> getUnusualOccurences() {
		return unusualOccurences;
	}

	public void setPatientDocuments(Set<PatientDocument> patientDocuments) {
		this.patientDocuments = patientDocuments;
	}

	public Set<PatientDocument> getPatientDocuments() {
		return patientDocuments;
	}

	public void setAllergys(Set<Allergy> allergys) {
		this.allergys = allergys;
	}

	public Set<Allergy> getAllergys() {
		return allergys;
	}

	public void setImmunizations(Set<Immunization> immunizations) {
		this.immunizations = immunizations;
	}

	public Set<Immunization> getImmunizations() {
		return immunizations;
	}

	public void setHealthNumber(String healthNumber) {
		this.healthNumber = healthNumber;
	}

	public String getHealthNumber() {

		return healthNumber;

	}

	public void setVitalValues(Set<VitalValue> vitalValues) {
		this.vitalValues = vitalValues;
	}

	public Set<VitalValue> getVitalValues() {
		return vitalValues;
	}

	public void setHistory(History history) {
		this.history = history;
	}

	public History getHistory() {

		if (history == null)
			history = new com.oreon.cerebrum.patient.History();
		return history;

	}

	public void setEncounters(
			Set<com.oreon.cerebrum.encounter.Encounter> encounters) {
		this.encounters = encounters;
	}

	public Set<com.oreon.cerebrum.encounter.Encounter> getEncounters() {
		return encounters;
	}

	public void setAppliedCharts(
			Set<com.oreon.cerebrum.charts.AppliedChart> appliedCharts) {
		this.appliedCharts = appliedCharts;
	}

	public Set<com.oreon.cerebrum.charts.AppliedChart> getAppliedCharts() {
		return appliedCharts;
	}

	public void setChartProcedures(
			Set<com.oreon.cerebrum.charts.ChartProcedure> chartProcedures) {
		this.chartProcedures = chartProcedures;
	}

	public Set<com.oreon.cerebrum.charts.ChartProcedure> getChartProcedures() {
		return chartProcedures;
	}

	public void setBed(com.oreon.cerebrum.facility.Bed bed) {
		this.bed = bed;
	}

	public com.oreon.cerebrum.facility.Bed getBed() {

		return bed;

	}

	public void setChronicConditions(
			Set<com.oreon.cerebrum.ddx.ChronicCondition> chronicConditions) {
		this.chronicConditions = chronicConditions;
	}

	public Set<com.oreon.cerebrum.ddx.ChronicCondition> getChronicConditions() {
		return chronicConditions;
	}

	@Transient
	public String getDisplayName() {
		try {
			return super.getDisplayName();
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

	@Transient
	public String getPopupInfo() {
		try {
			return age + " " + gender;
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

	//Empty setter , needed for richfaces autocomplete to work 
	public void setDisplayName(String name) {
	}

	/** This method is used by hibernate full text search - override to add additional fields
	 * @see org.witchcraft.model.support.BaseEntity#retrieveSearchableFieldsArray()
	 */
	@Override
	public List<String> listSearchableFields() {
		List<String> listSearchableFields = new ArrayList<String>();
		listSearchableFields.addAll(super.listSearchableFields());

		listSearchableFields.add("healthNumber");

		listSearchableFields.add("address.streetAddress");

		listSearchableFields.add("address.city");

		listSearchableFields.add("address.State");

		listSearchableFields.add("address.phone");

		listSearchableFields.add("history.medicalHistory");

		listSearchableFields.add("history.socialHistory");

		listSearchableFields.add("history.familyHistory");

		listSearchableFields.add("history.medications");

		listSearchableFields.add("history.allergies");

		return listSearchableFields;
	}

	@Field(index = Index.YES, name = "searchData")
	@Analyzer(definition = "entityAnalyzer")
	public String getSearchData() {
		StringBuilder builder = new StringBuilder();

		builder.append(getHealthNumber() + " ");

		if (getBed() != null)
			builder.append("bed:" + getBed().getDisplayName() + " ");

		for (BaseEntity e : admissions) {
			builder.append(e.getDisplayName() + " ");
		}

		for (BaseEntity e : prescriptions) {
			builder.append(e.getDisplayName() + " ");
		}

		for (BaseEntity e : unusualOccurences) {
			builder.append(e.getDisplayName() + " ");
		}

		for (BaseEntity e : patientDocuments) {
			builder.append(e.getDisplayName() + " ");
		}

		for (BaseEntity e : allergys) {
			builder.append(e.getDisplayName() + " ");
		}

		for (BaseEntity e : immunizations) {
			builder.append(e.getDisplayName() + " ");
		}

		for (BaseEntity e : vitalValues) {
			builder.append(e.getDisplayName() + " ");
		}

		for (BaseEntity e : encounters) {
			builder.append(e.getDisplayName() + " ");
		}

		for (BaseEntity e : appliedCharts) {
			builder.append(e.getDisplayName() + " ");
		}

		for (BaseEntity e : chartProcedures) {
			builder.append(e.getDisplayName() + " ");
		}

		return builder.toString();
	}

	/*
	<param name="bedId" value="#{bedId}" />
	
	 */

}
