package com.oreon.cerebrum.ddx;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.ManyToMany;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Transient;

import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.witchcraft.base.entity.BaseEntity;

//Impl 

/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

/**
 * 
 *
 */

@MappedSuperclass
public class ChronicConditionBase extends BaseEntity {
	private static final long serialVersionUID = 1358837921L;

	@Column(unique = false)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String name

	;

	@ManyToMany(mappedBy = "chronicConditions")
	private Set<com.oreon.cerebrum.patient.Patient> patients = new HashSet<com.oreon.cerebrum.patient.Patient>();

	public void addPatient(com.oreon.cerebrum.patient.Patient patient) {

		this.patients.add(patient);
	}

	@Transient
	public List<com.oreon.cerebrum.patient.Patient> getListPatients() {
		return new ArrayList<com.oreon.cerebrum.patient.Patient>(patients);
	}

	//JSF Friendly function to get count of collections
	public int getPatientsCount() {
		return patients.size();
	}

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "chronicCondition_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<com.oreon.cerebrum.charts.Chart> charts = new HashSet<com.oreon.cerebrum.charts.Chart>();

	public void addChart(com.oreon.cerebrum.charts.Chart chart) {

		chart.setChronicCondition((ChronicCondition) this);

		this.charts.add(chart);
	}

	@Transient
	public List<com.oreon.cerebrum.charts.Chart> getListCharts() {
		return new ArrayList<com.oreon.cerebrum.charts.Chart>(charts);
	}

	//JSF Friendly function to get count of collections
	public int getChartsCount() {
		return charts.size();
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {

		return name;

	}

	public void setPatients(Set<com.oreon.cerebrum.patient.Patient> patients) {
		this.patients = patients;
	}

	public Set<com.oreon.cerebrum.patient.Patient> getPatients() {
		return patients;
	}

	public void setCharts(Set<com.oreon.cerebrum.charts.Chart> charts) {
		this.charts = charts;
	}

	public Set<com.oreon.cerebrum.charts.Chart> getCharts() {
		return charts;
	}

	@Transient
	public String getDisplayName() {
		try {
			return name;
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

	//Empty setter , needed for richfaces autocomplete to work 
	public void setDisplayName(String name) {
	}

	/** This method is used by hibernate full text search - override to add additional fields
	 * @see org.witchcraft.model.support.BaseEntity#retrieveSearchableFieldsArray()
	 */
	@Override
	public List<String> listSearchableFields() {
		List<String> listSearchableFields = new ArrayList<String>();
		listSearchableFields.addAll(super.listSearchableFields());

		listSearchableFields.add("name");

		return listSearchableFields;
	}

	@Field(index = Index.YES, name = "searchData")
	@Analyzer(definition = "entityAnalyzer")
	public String getSearchData() {
		StringBuilder builder = new StringBuilder();

		builder.append(getName() + " ");

		for (BaseEntity e : charts) {
			builder.append(e.getDisplayName() + " ");
		}

		return builder.toString();
	}

	/*
	
	 */

}
