package com.oreon.cerebrum.ddx;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.validator.constraints.Length;
import org.witchcraft.base.entity.BaseEntity;

//Impl 

/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

/**
 * 
 *
 */

@MappedSuperclass
public class DiseaseBase extends BaseEntity {
	private static final long serialVersionUID = 714241030L;

	@Column(unique = false)
	protected com.oreon.cerebrum.patient.Gender gender

	;

	@NotNull
	@Length(min = 1, max = 250)
	@Column(unique = true)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String name

	;

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "relatedDisease_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<Disease> differentialDiagnoses = new HashSet<Disease>();

	public void addDifferentialDiagnose(Disease differentialDiagnose) {

		differentialDiagnose.setRelatedDisease((Disease) this);

		this.differentialDiagnoses.add(differentialDiagnose);
	}

	@Transient
	public List<com.oreon.cerebrum.ddx.Disease> getListDifferentialDiagnoses() {
		return new ArrayList<com.oreon.cerebrum.ddx.Disease>(
				differentialDiagnoses);
	}

	//JSF Friendly function to get count of collections
	public int getDifferentialDiagnosesCount() {
		return differentialDiagnoses.size();
	}

	@ManyToOne(optional = false, fetch = FetchType.LAZY)
	@JoinColumn(name = "relatedDisease_id", nullable = false, updatable = true)
	protected Disease relatedDisease

	;

	@ManyToOne(optional = true, fetch = FetchType.LAZY)
	@JoinColumn(name = "conditionCategory_id", nullable = true, updatable = true)
	protected ConditionCategory conditionCategory

	;

	public void setGender(com.oreon.cerebrum.patient.Gender gender) {
		this.gender = gender;
	}

	public com.oreon.cerebrum.patient.Gender getGender() {

		return gender;

	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {

		return name;

	}

	public void setDifferentialDiagnoses(Set<Disease> differentialDiagnoses) {
		this.differentialDiagnoses = differentialDiagnoses;
	}

	public Set<Disease> getDifferentialDiagnoses() {
		return differentialDiagnoses;
	}

	public void setRelatedDisease(Disease relatedDisease) {
		this.relatedDisease = relatedDisease;
	}

	public Disease getRelatedDisease() {

		return relatedDisease;

	}

	public void setConditionCategory(ConditionCategory conditionCategory) {
		this.conditionCategory = conditionCategory;
	}

	public ConditionCategory getConditionCategory() {

		return conditionCategory;

	}

	@Transient
	public String getDisplayName() {
		try {
			return name;
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

	//Empty setter , needed for richfaces autocomplete to work 
	public void setDisplayName(String name) {
	}

	/** This method is used by hibernate full text search - override to add additional fields
	 * @see org.witchcraft.model.support.BaseEntity#retrieveSearchableFieldsArray()
	 */
	@Override
	public List<String> listSearchableFields() {
		List<String> listSearchableFields = new ArrayList<String>();
		listSearchableFields.addAll(super.listSearchableFields());

		listSearchableFields.add("name");

		return listSearchableFields;
	}

	@Field(index = Index.YES, name = "searchData")
	@Analyzer(definition = "entityAnalyzer")
	public String getSearchData() {
		StringBuilder builder = new StringBuilder();

		builder.append(getName() + " ");

		if (getRelatedDisease() != null)
			builder.append("relatedDisease:"
					+ getRelatedDisease().getDisplayName() + " ");

		if (getConditionCategory() != null)
			builder.append("conditionCategory:"
					+ getConditionCategory().getDisplayName() + " ");

		for (BaseEntity e : differentialDiagnoses) {
			builder.append(e.getDisplayName() + " ");
		}

		return builder.toString();
	}

	/*
	<param name="relatedDiseaseId" value="#{relatedDiseaseId}" />
	<param name="conditionCategoryId" value="#{conditionCategoryId}" />
	
	 */

}
