package com.oreon.cerebrum.ddx;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.Transient;

import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.witchcraft.base.entity.BaseEntity;

//Impl 

/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

/**
 * 
 *
 */

@MappedSuperclass
public class PatientFindingBase extends BaseEntity {
	private static final long serialVersionUID = -901678194L;

	@ManyToOne(optional = false, fetch = FetchType.LAZY)
	@JoinColumn(name = "finding_id", nullable = false, updatable = true)
	protected Finding finding = new Finding();

	@ManyToOne(optional = false, fetch = FetchType.LAZY)
	@JoinColumn(name = "patientDiffDx_id", nullable = false, updatable = true)
	protected PatientDiffDx patientDiffDx

	;

	public void setFinding(Finding finding) {
		this.finding = finding;
	}

	public Finding getFinding() {

		return finding;

	}

	public void setPatientDiffDx(PatientDiffDx patientDiffDx) {
		this.patientDiffDx = patientDiffDx;
	}

	public PatientDiffDx getPatientDiffDx() {

		return patientDiffDx;

	}

	@Transient
	public String getDisplayName() {
		try {
			return finding + "";
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

	//Empty setter , needed for richfaces autocomplete to work 
	public void setDisplayName(String name) {
	}

	/** This method is used by hibernate full text search - override to add additional fields
	 * @see org.witchcraft.model.support.BaseEntity#retrieveSearchableFieldsArray()
	 */
	@Override
	public List<String> listSearchableFields() {
		List<String> listSearchableFields = new ArrayList<String>();
		listSearchableFields.addAll(super.listSearchableFields());

		return listSearchableFields;
	}

	@Field(index = Index.YES, name = "searchData")
	@Analyzer(definition = "entityAnalyzer")
	public String getSearchData() {
		StringBuilder builder = new StringBuilder();

		if (getFinding() != null)
			builder.append("finding:" + getFinding().getDisplayName() + " ");

		if (getPatientDiffDx() != null)
			builder.append("patientDiffDx:"
					+ getPatientDiffDx().getDisplayName() + " ");

		return builder.toString();
	}

	/*
	<param name="findingId" value="#{findingId}" />
	<param name="patientDiffDxId" value="#{patientDiffDxId}" />
	
	 */

}
